INSERT INTO Utilisateur (idUtilisateur, prenom, nom, email, password, dateInscription, activation_token, activation_token_expiration_date, refresh_token, refresh_token_expiration_date, reset_passwd_token, reset_passwd_token_expiration_date, role)
VALUES ('814e8485-e352-41c9-b134-1a10db2e72b4', 'Ryder', 'Quigley', 'retha76@lowe.com', '$2y$10$p3RkJ45wSw2qatC5gvdCiOgxfHn.wWcDHAn/7QL0qLJ84EXEaWAbK', '1973-05-17', '', '', '', '', '', '', '3');
INSERT INTO Utilisateur (idUtilisateur, prenom, nom, email, password, dateInscription, activation_token, activation_token_expiration_date, refresh_token, refresh_token_expiration_date, reset_passwd_token, reset_passwd_token_expiration_date, role)
VALUES ('bd32d15e-e809-41db-90de-4ee48678df66', 'Rhianna', 'Wilderman', 'qwalsh@hotmail.com', '$2y$10$5cOl4v8J8DQpwT6E6oaWG.6C0ldS1vQDypTddq.fAhLl5vy.ruN..', '1983-09-17', '', '', '', '', '', '', '3');
INSERT INTO Utilisateur (idUtilisateur, prenom, nom, email, password, dateInscription, activation_token, activation_token_expiration_date, refresh_token, refresh_token_expiration_date, reset_passwd_token, reset_passwd_token_expiration_date, role)
VALUES ('c39f1fa1-cf61-48b4-9c6a-902b3620a5b7', 'Providenci', 'Upton', 'zlindgren@gmail.com', '$2y$10$gFKlkLPomtzG3BJoYmfp.ehTnmUKOqsnUyBsFDY0EoEYbvPxNo2jm', '1993-02-01', '', '', '', '', '', '', '3');
INSERT INTO Utilisateur (idUtilisateur, prenom, nom, email, password, dateInscription, activation_token, activation_token_expiration_date, refresh_token, refresh_token_expiration_date, reset_passwd_token, reset_passwd_token_expiration_date, role)
VALUES ('a16d9855-06f0-4ca7-90af-aed254698092', 'Lucious', 'Raynor', 'toy.jena@davis.org', '$2y$10$uQMHvpfqF7goP9CpsIte..hw6FFWE6gxLYsTru/Qiw2U/s0yid0aS', '1971-12-30', '', '', '', '', '', '', '1');
INSERT INTO Utilisateur (idUtilisateur, prenom, nom, email, password, dateInscription, activation_token, activation_token_expiration_date, refresh_token, refresh_token_expiration_date, reset_passwd_token, reset_passwd_token_expiration_date, role)
VALUES ('d149f4eb-1835-40e7-b808-2ae88c550cb7', 'Marvin', 'Jones', 'zkling@hotmail.com', '$2y$10$cWnHj0TyZLFq2BZbMSlEKO6nbg85Ym1s.jf5rDjtPeDKMPy5pPCqa', '1991-08-10', '', '', '', '', '', '', '2');
INSERT INTO Utilisateur (idUtilisateur, prenom, nom, email, password, dateInscription, activation_token, activation_token_expiration_date, refresh_token, refresh_token_expiration_date, reset_passwd_token, reset_passwd_token_expiration_date, role)
VALUES ('681d897d-2324-4723-82c9-a5051229101b', 'Hortense', 'Sawayn', 'benjamin76@reichel.com', '$2y$10$JN5rq5SXZEKDL8tagdjsouXLyma02APU40dvog.wEhr8hf67hKN0S', '1979-07-17', '', '', '', '', '', '', '1');
INSERT INTO Utilisateur (idUtilisateur, prenom, nom, email, password, dateInscription, activation_token, activation_token_expiration_date, refresh_token, refresh_token_expiration_date, reset_passwd_token, reset_passwd_token_expiration_date, role)
VALUES ('ab726897-446b-441d-b08f-40421154f659', 'Demarco', 'Jaskolski', 'nblock@yahoo.com', '$2y$10$zzFIV84tsxL//xMm/2uqte46/X.A99hl9RPFtlb6wZkDfJ2dQa94m', '2023-04-09', '', '', '', '', '', '', '1');
INSERT INTO Utilisateur (idUtilisateur, prenom, nom, email, password, dateInscription, activation_token, activation_token_expiration_date, refresh_token, refresh_token_expiration_date, reset_passwd_token, reset_passwd_token_expiration_date, role)
VALUES ('45bee910-3049-4fc1-a1cb-de26a3a883d2', 'Shad', 'Frami', 'jaida.bruen@yahoo.com', '$2y$10$3AhHrBSdDiR8RUcocp1ni.2myrY3IQC0KfX2fIS0FlmD0oVm78tFK', '2023-04-19', '', '', '', '', '', '', '1');
INSERT INTO Utilisateur (idUtilisateur, prenom, nom, email, password, dateInscription, activation_token, activation_token_expiration_date, refresh_token, refresh_token_expiration_date, reset_passwd_token, reset_passwd_token_expiration_date, role)
VALUES ('621d5f18-9edf-4f58-925e-76d4a37ccb09', 'Madilyn', 'Feest', 'karlie46@yahoo.com', '$2y$10$9my0d3qP09vx0cF2eUqSu.SPbQqRA8N3z3KiJLvBxvcnekxW2h3mu', '2007-03-29', '', '', '', '', '', '', '1');
INSERT INTO Utilisateur (idUtilisateur, prenom, nom, email, password, dateInscription, activation_token, activation_token_expiration_date, refresh_token, refresh_token_expiration_date, reset_passwd_token, reset_passwd_token_expiration_date, role)
VALUES ('0f967a23-36dc-4536-967b-f134e2e08323', 'Mathew', 'Hand', 'hettinger.madisen@hotmail.com', '$2y$10$ZXm9equDyTTexj3CGQNgmOYMdWqIVhcm5ZEQRb1F2IwOZuOKU4nfy', '1985-01-25', '', '', '', '', '', '', '2');
INSERT INTO Utilisateur (idUtilisateur, prenom, nom, email, password, dateInscription, activation_token, activation_token_expiration_date, refresh_token, refresh_token_expiration_date, reset_passwd_token, reset_passwd_token_expiration_date, role)
VALUES ('47c5ef92-5317-46d5-91cb-c0d41bc7f424', 'Rhoda', 'Powlowski', 'rboyle@grant.com', '$2y$10$Ri6nBNG9QJHvD8qcuUT6eezD9DgXiltIAWx9ra9M97CtII4W0jpS.', '1978-03-31', '', '', '', '', '', '', '2');
INSERT INTO Utilisateur (idUtilisateur, prenom, nom, email, password, dateInscription, activation_token, activation_token_expiration_date, refresh_token, refresh_token_expiration_date, reset_passwd_token, reset_passwd_token_expiration_date, role)
VALUES ('2700566d-a407-4d11-831d-7e2bfec9532b', 'Jerry', 'Hackett', 'zachery.marvin@yahoo.com', '$2y$10$3yRwycERi2IsDf7.KOv5Cux8b5gL.LuE/SlMXXxr6qjUJaIFx8BM.', '1978-05-05', '', '', '', '', '', '', '2');
INSERT INTO Utilisateur (idUtilisateur, prenom, nom, email, password, dateInscription, activation_token, activation_token_expiration_date, refresh_token, refresh_token_expiration_date, reset_passwd_token, reset_passwd_token_expiration_date, role)
VALUES ('1bef10bb-63cb-4302-b532-bf35d2a1ce96', 'Lazaro', 'Kunze', 'enrico48@ruecker.net', '$2y$10$1i3Y/IqTGXjR6yD7E5BJX.g6aorNsKnadMmrY.O.xp1OpshcF7YS.', '2014-03-16', '', '', '', '', '', '', '1');
INSERT INTO Utilisateur (idUtilisateur, prenom, nom, email, password, dateInscription, activation_token, activation_token_expiration_date, refresh_token, refresh_token_expiration_date, reset_passwd_token, reset_passwd_token_expiration_date, role)
VALUES ('a9fb6a7b-31de-4b11-aca7-6373bf9071b5', 'Gilda', 'Collier', 'ella91@kuhlman.biz', '$2y$10$mhM6a8tZMXBYoTDJXfNBcOsZSNbkRZIIqrO2tMkAAkQgSA2w9kwvq', '2006-05-08', '', '', '', '', '', '', '2');
INSERT INTO Utilisateur (idUtilisateur, prenom, nom, email, password, dateInscription, activation_token, activation_token_expiration_date, refresh_token, refresh_token_expiration_date, reset_passwd_token, reset_passwd_token_expiration_date, role)
VALUES ('71bb42ab-cec7-446c-865e-a749327cb7ae', 'Corrine', 'Medhurst', 'lina.koepp@yahoo.com', '$2y$10$IoN6GFBQQUBb9wrPqF9by.rRTYBzdr.BFs0h3rg.E30Fv75IE0g4i', '2020-12-04', '', '', '', '', '', '', '2');
INSERT INTO Utilisateur (idUtilisateur, prenom, nom, email, password, dateInscription, activation_token, activation_token_expiration_date, refresh_token, refresh_token_expiration_date, reset_passwd_token, reset_passwd_token_expiration_date, role)
VALUES ('5dd63fdc-d451-41b5-a691-43a8cea54283', 'Austyn', 'Armstrong', 'kylie.dietrich@yahoo.com', '$2y$10$SzBCAzPaQfjLdG9ygvV/cObkwiLC75mFKp3feTwTXvJWuunO3CZAe', '2021-07-21', '', '', '', '', '', '', '1');
INSERT INTO Utilisateur (idUtilisateur, prenom, nom, email, password, dateInscription, activation_token, activation_token_expiration_date, refresh_token, refresh_token_expiration_date, reset_passwd_token, reset_passwd_token_expiration_date, role)
VALUES ('1f26001c-70ff-4ad3-adf2-d42635b51989', 'Jacky', 'Pfannerstill', 'eugene.oconnell@berge.com', '$2y$10$O6L31n8Ahp42Z4fJqFwd9OXY/5LPvdN2Ji5tqGvJZB24uOpaZzbPS', '1978-03-02', '', '', '', '', '', '', '1');
INSERT INTO Utilisateur (idUtilisateur, prenom, nom, email, password, dateInscription, activation_token, activation_token_expiration_date, refresh_token, refresh_token_expiration_date, reset_passwd_token, reset_passwd_token_expiration_date, role)
VALUES ('4388cbe0-b6ca-4d50-9481-5de869225e42', 'Seth', 'Bosco', 'dickens.mario@strosin.net', '$2y$10$PLzHw1Uoq0AYzv.SRraqAeMXL/0zz2VOzW1eyNbU3p5WwhOZpY7YW', '2012-12-02', '', '', '', '', '', '', '2');
INSERT INTO Utilisateur (idUtilisateur, prenom, nom, email, password, dateInscription, activation_token, activation_token_expiration_date, refresh_token, refresh_token_expiration_date, reset_passwd_token, reset_passwd_token_expiration_date, role)
VALUES ('1a114541-79f1-4f85-b5f4-e9c07c5c2d79', 'Freddie', 'Nicolas', 'martin.luettgen@kuhic.com', '$2y$10$wEwl.IbDoBsM6bs7pU0h9..ZHd85BZWyvZSgpOb3HRHgTtrhlDc4e', '1972-10-27', '', '', '', '', '', '', '2');
INSERT INTO Utilisateur (idUtilisateur, prenom, nom, email, password, dateInscription, activation_token, activation_token_expiration_date, refresh_token, refresh_token_expiration_date, reset_passwd_token, reset_passwd_token_expiration_date, role)
VALUES ('de472d4d-798f-4e8c-b09e-1fdede7eca0a', 'Jazmyne', 'Osinski', 'donna.kunze@grant.net', '$2y$10$KWrcp.fz2qZmyFF5ntPv/OsqsRZtEAOqNJb6dT0IB35KfrMaDj29a', '1970-07-10', '', '', '', '', '', '', '2');
INSERT INTO Utilisateur (idUtilisateur, prenom, nom, email, password, dateInscription, activation_token, activation_token_expiration_date, refresh_token, refresh_token_expiration_date, reset_passwd_token, reset_passwd_token_expiration_date, role)
VALUES ('8b27087b-598b-4fad-a040-a6ad1ae1b05c', 'Lucio', 'Nitzsche', 'padberg.sherman@walsh.com', '$2y$10$sQKCS/o9MiAnXBVrFzK/demfKTq9qtzgAQ/XSbpP5FWV2Ej2P.qdu', '2004-06-24', '', '', '', '', '', '', '2');
INSERT INTO Utilisateur (idUtilisateur, prenom, nom, email, password, dateInscription, activation_token, activation_token_expiration_date, refresh_token, refresh_token_expiration_date, reset_passwd_token, reset_passwd_token_expiration_date, role)
VALUES ('b154cc06-5128-496b-834d-1460a5f40913', 'Jerome', 'Schuster', 'lakin.carroll@gmail.com', '$2y$10$7UcnAld9I0Gg7GuQCof2ie5lHy9PLJ9ANYyJHnbRy5zjYIFfNOm4O', '1992-03-13', '', '', '', '', '', '', '1');
INSERT INTO Utilisateur (idUtilisateur, prenom, nom, email, password, dateInscription, activation_token, activation_token_expiration_date, refresh_token, refresh_token_expiration_date, reset_passwd_token, reset_passwd_token_expiration_date, role)
VALUES ('f81d5fb3-4108-4824-b8d7-9278abdd3635', 'Johnpaul', 'Sipes', 'janae.sporer@hane.com', '$2y$10$1kBzhEx5hszSmPPBcKVo0uINgayhblZLYLj3ii3/1wTkpoAsxPo1y', '2022-01-16', '', '', '', '', '', '', '1');
INSERT INTO Utilisateur (idUtilisateur, prenom, nom, email, password, dateInscription, activation_token, activation_token_expiration_date, refresh_token, refresh_token_expiration_date, reset_passwd_token, reset_passwd_token_expiration_date, role)
VALUES ('cf07b5b4-a63a-4028-8044-3896161af2ed', 'Ryder', 'Feest', 'oschultz@mosciski.com', '$2y$10$IQUGF03RxmV.ss.gGhhZ2OoV5yIEqibIP5OtVPak8SBMICgBEbHGi', '2015-03-28', '', '', '', '', '', '', '2');
INSERT INTO Utilisateur (idUtilisateur, prenom, nom, email, password, dateInscription, activation_token, activation_token_expiration_date, refresh_token, refresh_token_expiration_date, reset_passwd_token, reset_passwd_token_expiration_date, role)
VALUES ('53b1188f-da2c-4560-912a-cd4d5a1a4498', 'Kole', 'Monahan', 'nova47@gmail.com', '$2y$10$A.MMAAHd3xAoeZw56qaYBOP6pHUgigCBuAeAGIzWhuZVPFYqZILrm', '1977-10-02', '', '', '', '', '', '', '1');
INSERT INTO Utilisateur (idUtilisateur, prenom, nom, email, password, dateInscription, activation_token, activation_token_expiration_date, refresh_token, refresh_token_expiration_date, reset_passwd_token, reset_passwd_token_expiration_date, role)
VALUES ('b63177de-2e6e-4b23-aba1-21e96ced5c0d', 'Carlie', 'Streich', 'summer.jenkins@franecki.com', '$2y$10$.wkwSB8AKBTo9nylrlteG.PJOWbRtjZ2fZ3gozUKznumJNYGk07am', '1976-03-11', '', '', '', '', '', '', '1');
INSERT INTO Utilisateur (idUtilisateur, prenom, nom, email, password, dateInscription, activation_token, activation_token_expiration_date, refresh_token, refresh_token_expiration_date, reset_passwd_token, reset_passwd_token_expiration_date, role)
VALUES ('56c77dd0-6346-4132-b37c-fe210f061d6b', 'Rahsaan', 'Murazik', 'isabel.hodkiewicz@mueller.com', '$2y$10$iKIHx79L2f4XLorMpgh8IurBdZ59kP9gmVnVjwvSzuAwvFiMBOyR6', '1976-02-10', '', '', '', '', '', '', '2');
INSERT INTO Utilisateur (idUtilisateur, prenom, nom, email, password, dateInscription, activation_token, activation_token_expiration_date, refresh_token, refresh_token_expiration_date, reset_passwd_token, reset_passwd_token_expiration_date, role)
VALUES ('a066e97d-e2d6-437f-9c3c-0ab55e733fe2', 'Delpha', 'Hackett', 'runolfsson.shyann@kshlerin.biz', '$2y$10$WLYbo0kSgxVyLhjGPqNl3ebmHvM/VqAZw5YZb6N/MLQNKSl6gYVFK', '1979-08-10', '', '', '', '', '', '', '1');
INSERT INTO Utilisateur (idUtilisateur, prenom, nom, email, password, dateInscription, activation_token, activation_token_expiration_date, refresh_token, refresh_token_expiration_date, reset_passwd_token, reset_passwd_token_expiration_date, role)
VALUES ('e97308c9-3c3e-4f4e-83e2-61b13cab7590', 'Kimberly', 'Moore', 'ecrist@yahoo.com', '$2y$10$syT2iVt5LdS4RFGHy7.N2ONDJIglHSWxYi6rUPgI2r6iypyymwq5a', '2011-03-19', '', '', '', '', '', '', '1');
INSERT INTO Utilisateur (idUtilisateur, prenom, nom, email, password, dateInscription, activation_token, activation_token_expiration_date, refresh_token, refresh_token_expiration_date, reset_passwd_token, reset_passwd_token_expiration_date, role)
VALUES ('e623185d-02d8-4508-accf-4c845d14a67f', 'Emelie', 'Gutmann', 'yost.michael@beatty.com', '$2y$10$a4SgEdJJuDWfHTqMiZkl3uHpDI4hQI43YsuJn2VgBJ.99jyV1hnKm', '1972-08-26', '', '', '', '', '', '', '1');
INSERT INTO Utilisateur (idUtilisateur, prenom, nom, email, password, dateInscription, activation_token, activation_token_expiration_date, refresh_token, refresh_token_expiration_date, reset_passwd_token, reset_passwd_token_expiration_date, role)
VALUES ('0ac95fb4-2ba0-4157-ad23-f9ab94af44d4', 'Kattie', 'Boyer', 'carmel64@yahoo.com', '$2y$10$Mv6.GSPh2amKqMxIgZ1FDe.9E.0rt78giSGYk4sgFTkHvmc8cHyci', '1984-06-24', '', '', '', '', '', '', '2');
INSERT INTO Utilisateur (idUtilisateur, prenom, nom, email, password, dateInscription, activation_token, activation_token_expiration_date, refresh_token, refresh_token_expiration_date, reset_passwd_token, reset_passwd_token_expiration_date, role)
VALUES ('e42767df-e03d-4b46-a33b-ea39a307f44c', 'Stanley', 'Nader', 'marks.bud@yahoo.com', '$2y$10$mGE/ObhdZpGZh7w90iHuOuaUP3JYX1sd0Dlua.reFdNv.y5jOACby', '1981-02-22', '', '', '', '', '', '', '1');
INSERT INTO Utilisateur (idUtilisateur, prenom, nom, email, password, dateInscription, activation_token, activation_token_expiration_date, refresh_token, refresh_token_expiration_date, reset_passwd_token, reset_passwd_token_expiration_date, role)
VALUES ('d594c7b7-c2a8-4c37-9835-73e319f53119', 'Cassandra', 'Halvorson', 'zoila38@harris.net', '$2y$10$RobiGkmG8dw9RMuAwgsvLe5pLtSjfLxNSmoaoh51ED7r2TgcdLtZi', '2000-02-15', '', '', '', '', '', '', '2');
INSERT INTO Utilisateur (idUtilisateur, prenom, nom, email, password, dateInscription, activation_token, activation_token_expiration_date, refresh_token, refresh_token_expiration_date, reset_passwd_token, reset_passwd_token_expiration_date, role)
VALUES ('a8a1d119-296f-4c15-b9e7-cb9c87aa6912', 'Wilbert', 'Balistreri', 'leonora.mccullough@hotmail.com', '$2y$10$1e/rZtLdfPyiQyvZarlRJ.E8h0q9mR3UktPyJexqFszj8Igdh.AlO', '1990-01-29', '', '', '', '', '', '', '2');
INSERT INTO Utilisateur (idUtilisateur, prenom, nom, email, password, dateInscription, activation_token, activation_token_expiration_date, refresh_token, refresh_token_expiration_date, reset_passwd_token, reset_passwd_token_expiration_date, role)
VALUES ('4989fc59-1d66-4e45-80a4-68319d2c6285', 'Oma', 'Gerhold', 'ybailey@leannon.biz', '$2y$10$uLQDcGTGkFwtyLWt3094L.cQefJ0OiENq9Tmj8jaxERX40o0yaWYG', '2014-03-04', '', '', '', '', '', '', '2');
INSERT INTO Utilisateur (idUtilisateur, prenom, nom, email, password, dateInscription, activation_token, activation_token_expiration_date, refresh_token, refresh_token_expiration_date, reset_passwd_token, reset_passwd_token_expiration_date, role)
VALUES ('5ccfbc63-e38c-4f3f-ad33-f9e14d24731d', 'Doris', 'Beier', 'nitzsche.jana@pfeffer.com', '$2y$10$8IPCCTg/c2fVtDJ4u4Lq9eN40Y68.ok8sP5S0eqUshHkooZuTWgHm', '1975-07-09', '', '', '', '', '', '', '1');
INSERT INTO Utilisateur (idUtilisateur, prenom, nom, email, password, dateInscription, activation_token, activation_token_expiration_date, refresh_token, refresh_token_expiration_date, reset_passwd_token, reset_passwd_token_expiration_date, role)
VALUES ('28f13433-168f-4d36-aa08-e8bcfc04067e', 'Shyann', 'Goyette', 'clinton06@gmail.com', '$2y$10$j7nhwCnQbto86td64kH4qu.H9eRz5mDzcAi3gK2MfDbB1CMyGxaE6', '1986-03-04', '', '', '', '', '', '', '1');
INSERT INTO Utilisateur (idUtilisateur, prenom, nom, email, password, dateInscription, activation_token, activation_token_expiration_date, refresh_token, refresh_token_expiration_date, reset_passwd_token, reset_passwd_token_expiration_date, role)
VALUES ('aa3ce345-7f69-4638-9446-977000f3b680', 'Enrico', 'Fritsch', 'osinski.josefa@hotmail.com', '$2y$10$PLAP77S8d2mS0YB9.Mk/1eeLHTG1ePY36l4Ko7aazWaEFAg.qLM.K', '2007-10-20', '', '', '', '', '', '', '2');
INSERT INTO Utilisateur (idUtilisateur, prenom, nom, email, password, dateInscription, activation_token, activation_token_expiration_date, refresh_token, refresh_token_expiration_date, reset_passwd_token, reset_passwd_token_expiration_date, role)
VALUES ('e4c9e2c5-ba73-4d4f-8fe0-5dc058779564', 'Athena', 'Sporer', 'madisen.conroy@gmail.com', '$2y$10$PEvc7/t7EiWK7WvoTScIKOQ/rLxLJ2eoA8eNUfudRLaouEFgXKYLG', '1974-05-24', '', '', '', '', '', '', '1');
INSERT INTO Utilisateur (idUtilisateur, prenom, nom, email, password, dateInscription, activation_token, activation_token_expiration_date, refresh_token, refresh_token_expiration_date, reset_passwd_token, reset_passwd_token_expiration_date, role)
VALUES ('ba8bd5d5-46e2-4204-9bc1-dbd7b31c64b2', 'Jesus', 'Gaylord', 'lang.joana@gmail.com', '$2y$10$0FmpTA0fYS143nK8J3BvrO3s7QS.8K6/g1eTaTtVK/SRAwdUhjKSS', '2009-12-14', '', '', '', '', '', '', '1');
INSERT INTO Utilisateur (idUtilisateur, prenom, nom, email, password, dateInscription, activation_token, activation_token_expiration_date, refresh_token, refresh_token_expiration_date, reset_passwd_token, reset_passwd_token_expiration_date, role)
VALUES ('3f80506e-d862-4fa6-9f19-9f71535f8920', 'Janae', 'Bruen', 'kohler.neva@yahoo.com', '$2y$10$rg78echUWEQYBMNZGOOBi.Rst3HqqcCTXLNTJbYJVe31XjyD3XsHW', '1991-04-20', '', '', '', '', '', '', '2');
INSERT INTO Utilisateur (idUtilisateur, prenom, nom, email, password, dateInscription, activation_token, activation_token_expiration_date, refresh_token, refresh_token_expiration_date, reset_passwd_token, reset_passwd_token_expiration_date, role)
VALUES ('3c912aed-93f7-43b3-b71e-31f8214ab2b3', 'Oren', 'Goodwin', 'carleton30@hotmail.com', '$2y$10$51g.3ezLWZsZbpJYKm6lleAEw2c7UZonBr1n9MeVPxx7yxf75ornK', '1983-12-21', '', '', '', '', '', '', '2');
INSERT INTO Utilisateur (idUtilisateur, prenom, nom, email, password, dateInscription, activation_token, activation_token_expiration_date, refresh_token, refresh_token_expiration_date, reset_passwd_token, reset_passwd_token_expiration_date, role)
VALUES ('1a065403-9099-4de4-b023-4c8c548e2654', 'Alice', 'Robel', 'elvie.casper@stanton.com', '$2y$10$XpIg.Lg/clHWp.vAnbsw9ONa9eP0babZhtWSsMhkSasWQDT.mv9oS', '2008-05-17', '', '', '', '', '', '', '2');
INSERT INTO Utilisateur (idUtilisateur, prenom, nom, email, password, dateInscription, activation_token, activation_token_expiration_date, refresh_token, refresh_token_expiration_date, reset_passwd_token, reset_passwd_token_expiration_date, role)
VALUES ('15d76198-6219-492b-8212-ae0eae6f4b9a', 'Leslie', 'Cormier', 'qcorwin@yahoo.com', '$2y$10$Ejhijk7qxFUl3zyw1TnabOBHFQY7AYA5X.Dt0MWdnu8yqMV.ope2K', '2022-10-25', '', '', '', '', '', '', '2');
INSERT INTO Utilisateur (idUtilisateur, prenom, nom, email, password, dateInscription, activation_token, activation_token_expiration_date, refresh_token, refresh_token_expiration_date, reset_passwd_token, reset_passwd_token_expiration_date, role)
VALUES ('8d988175-90e4-417e-becd-c5e7c1256ccd', 'Oda', 'Lehner', 'vicente13@gmail.com', '$2y$10$CnjwhhVgeS4fHA1k7eprneBr4I.d4.r2eRrexOdoB3xs/cEeQ.r1K', '1972-08-08', '', '', '', '', '', '', '2');
INSERT INTO Utilisateur (idUtilisateur, prenom, nom, email, password, dateInscription, activation_token, activation_token_expiration_date, refresh_token, refresh_token_expiration_date, reset_passwd_token, reset_passwd_token_expiration_date, role)
VALUES ('90aafa54-2e78-46e3-91b4-5d2c75a1e8e4', 'Fernando', 'Hammes', 'esteban47@gmail.com', '$2y$10$ipPv8CWbG9rOSIwJRq.e/u4qzxRP9q0B8iPgeOgIBaJQYHEA8GLx.', '1980-02-13', '', '', '', '', '', '', '2');
INSERT INTO Utilisateur (idUtilisateur, prenom, nom, email, password, dateInscription, activation_token, activation_token_expiration_date, refresh_token, refresh_token_expiration_date, reset_passwd_token, reset_passwd_token_expiration_date, role)
VALUES ('516850fa-8907-4404-9dae-73b9608c0945', 'Allison', 'Mertz', 'leonor00@gmail.com', '$2y$10$O1dt54SdXU1HG5ehXucVMeaMs5FUxq3g.b5Wi6y8jku8cgTnBxoju', '1975-05-30', '', '', '', '', '', '', '2');
INSERT INTO Utilisateur (idUtilisateur, prenom, nom, email, password, dateInscription, activation_token, activation_token_expiration_date, refresh_token, refresh_token_expiration_date, reset_passwd_token, reset_passwd_token_expiration_date, role)
VALUES ('74ed2c7a-a782-408d-ac2f-0eea88bd1575', 'Roy', 'McCullough', 'maia.hudson@hotmail.com', '$2y$10$QsBYefJkXEhoydrHJQCCpOOI7bIZ/lIWJUp5sqiGDnhpb4kxgD58S', '1999-01-29', '', '', '', '', '', '', '1');
INSERT INTO Utilisateur (idUtilisateur, prenom, nom, email, password, dateInscription, activation_token, activation_token_expiration_date, refresh_token, refresh_token_expiration_date, reset_passwd_token, reset_passwd_token_expiration_date, role)
VALUES ('cf990a7f-19ee-48cd-8b1c-614316c6571d', 'Selena', 'Kemmer', 'marilou.williamson@goodwin.org', '$2y$10$/xCTSQXmnN3R6n4GkNPkKuXg/SQXkvBCBvoiasDOrhG93j2Q5A8ia', '1988-11-09', '', '', '', '', '', '', '1');
INSERT INTO Utilisateur (idUtilisateur, prenom, nom, email, password, dateInscription, activation_token, activation_token_expiration_date, refresh_token, refresh_token_expiration_date, reset_passwd_token, reset_passwd_token_expiration_date, role)
VALUES ('c4ac02dc-1398-4dd1-a09d-58a706738571', 'Brando', 'Marks', 'wlind@yahoo.com', '$2y$10$8hEGWKt.t1rhxMqvjiGvrem7uRvyjsSpTmciB3moi0yO4El8ACqtO', '2008-11-08', '', '', '', '', '', '', '2');