INSERT INTO Utilisateur (idUtilisateur, prenom, nom, email, password, dateInscription, activation_token, activation_token_expiration_date, refresh_token, refresh_token_expiration_date, reset_passwd_token, reset_passwd_token_expiration_date, role)
VALUES ('814e8485-e352-41c9-b134-1a10db2e72b4', 'Ryder', 'Quigley', 'retha76@lowe.com', '$2y$10$p3RkJ45wSw2qatC5gvdCiOgxfHn.wWcDHAn/7QL0qLJ84EXEaWAbK', '1973-05-17', NULL, NULL, NULL, NULL, NULL, NULL, '1');
INSERT INTO Utilisateur (idUtilisateur, prenom, nom, email, password, dateInscription, activation_token, activation_token_expiration_date, refresh_token, refresh_token_expiration_date, reset_passwd_token, reset_passwd_token_expiration_date, role)
VALUES ('bd32d15e-e809-41db-90de-4ee48678df66', 'Rhianna', 'Wilderman', 'qwalsh@hotmail.com', '$2y$10$5cOl4v8J8DQpwT6E6oaWG.6C0ldS1vQDypTddq.fAhLl5vy.ruN..', '1983-09-17', NULL, NULL, NULL, NULL, NULL, NULL, '1');
INSERT INTO Utilisateur (idUtilisateur, prenom, nom, email, password, dateInscription, activation_token, activation_token_expiration_date, refresh_token, refresh_token_expiration_date, reset_passwd_token, reset_passwd_token_expiration_date, role)
VALUES ('c39f1fa1-cf61-48b4-9c6a-902b3620a5b7', 'Providenci', 'Upton', 'zlindgren@gmail.com', '$2y$10$gFKlkLPomtzG3BJoYmfp.ehTnmUKOqsnUyBsFDY0EoEYbvPxNo2jm', '1993-02-01', NULL, NULL, NULL, NULL, NULL, NULL, '2');
INSERT INTO Utilisateur (idUtilisateur, prenom, nom, email, password, dateInscription, activation_token, activation_token_expiration_date, refresh_token, refresh_token_expiration_date, reset_passwd_token, reset_passwd_token_expiration_date, role)
VALUES ('a16d9855-06f0-4ca7-90af-aed254698092', 'Lucious', 'Raynor', 'toy.jena@davis.org', '$2y$10$uQMHvpfqF7goP9CpsIte..hw6FFWE6gxLYsTru/Qiw2U/s0yid0aS', '1971-12-30', NULL, NULL, NULL, NULL, NULL, NULL, '2');
INSERT INTO Utilisateur (idUtilisateur, prenom, nom, email, password, dateInscription, activation_token, activation_token_expiration_date, refresh_token, refresh_token_expiration_date, reset_passwd_token, reset_passwd_token_expiration_date, role)
VALUES ('d149f4eb-1835-40e7-b808-2ae88c550cb7', 'Marvin', 'Jones', 'zkling@hotmail.com', '$2y$10$cWnHj0TyZLFq2BZbMSlEKO6nbg85Ym1s.jf5rDjtPeDKMPy5pPCqa', '1991-08-10', NULL, NULL, NULL, NULL, NULL, NULL, '1');
